worker_processes 1;
daemon off;
error_log logs/error.log info;

events {
    worker_connections 1024;
}

http {
    include mime.types # not included in this repo

    lua_shared_dict local_cache 10m;

    server {
        listen 80;
        server_name localhost;

        location / {
            root html;
            index index.html index.htm;
        }
    }
}